// Ported from odoo portfolio/data.ts

export const MOCK_MODULES = [
  {
    id: 17,
    name: 'ai_backport_odoo16',
    shortdesc: 'AI Backport Odoo 16',
    summary: 'Backport of Odoo 19 AI core: includes agents, tools, topics, and embeddings.',
    state: 'installed',
    application: true,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Productivity'
  },
  {
    id: 18,
    name: 'ai_additional_providers',
    shortdesc: 'AI Additional Providers',
    summary: 'Extends AI Core with support for on-premises modules and custom model providers.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Productivity'
  },
  {
    id: 11,
    name: 'edi_engine',
    shortdesc: 'EDI Engine',
    summary: 'Configurable Electronic Data Interchange engine for partners, connections and runs.',
    state: 'uninstalled',
    application: true,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Administration'
  },
  {
    id: 12,
    name: 'hr_asset_assignment',
    shortdesc: 'HR Asset Assignment',
    summary: 'Streamlined module for managing internal resource assignments within the HR department.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Human Resources'
  },
  {
    id: 7,
    name: 'stock_aging_engine',
    shortdesc: 'Stock Aging Engine',
    summary: 'Analyze inventory movement to identify slow-moving or obsolete stock items.',
    state: 'installed',
    application: true,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Supply Chain'
  },
  {
    id: 14,
    name: 'odoo_google_places',
    shortdesc: 'Integration with Google Places API',
    summary: 'Google Places API integration with internal cost calculation and quota tracking.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Administration'
  },
  {
    id: 1,
    name: 'show_filtered_attribute_price_ecommerce',
    shortdesc: 'Show Filtered Attribute Price in eCommerce',
    summary: 'Dynamically updates product prices based on filtered attributes in shop view.',
    state: 'installed',
    website: 'https://apps.odoo.com/apps/modules/17.0/show_filtered_attribute_price_ecommerce',
    application: true,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Website'
  },
  {
    id: 2,
    name: 'logging_clean_up',
    shortdesc: 'Logging Cleanup',
    summary: 'Optimize database by automatically cleaning up old log entries to maintain speed.',
    state: 'uninstalled',
    website: 'https://apps.odoo.com/apps/modules/17.0/logging_clean_up',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Administration'
  },
  {
    id: 3,
    name: 'pickings_invoices_shortcuts',
    shortdesc: 'Pickings Invoices Shortcuts',
    summary: 'Direct navigation links between warehouse pickings and their invoices for faster workflows.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Supply Chain'
  },
  {
    id: 4,
    name: 'hr_phone_extension',
    shortdesc: 'HR Phone Extension Management',
    summary: 'Manage and track internal phone extensions for employees within the HR module.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Human Resources'
  },
  {
    id: 5,
    name: 'multi_company_product_selector',
    shortdesc: 'Multi-Company Product Visibility',
    summary: 'Control product visibility and selection in complex multi-company environments.',
    state: 'installed',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Sales'
  },
  {
    id: 6,
    name: 'sort_products_by_new_arrivals',
    shortdesc: 'Sort Products by New Arrivals',
    summary: 'Adds a sorting option to eCommerce to show recently added items first.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Website'
  },
  {
    id: 8,
    name: 'stock_gift_vouchers',
    shortdesc: 'Stock Gift Vouchers',
    summary: 'Integrate gift voucher functionality with inventory to track redemption and value.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Sales'
  },
  {
    id: 9,
    name: 'products_auto_show',
    shortdesc: 'products auto show Published Ecommerce',
    summary: 'Automates website product visibility based on stock levels and category rules.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Website'
  },
  {
    id: 10,
    name: 'asset_assignment_management',
    shortdesc: 'Asset Assignment Management',
    summary: 'Track physical asset item assignments to employees, departments, and locations.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Customizations'
  },
  {
    id: 13,
    name: 'hr_asset_settlement',
    shortdesc: 'HR Asset Settlement',
    summary: 'Visibility of employee asset assignments during HR settlement and re-join workflows.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Human Resources'
  },
  {
    id: 15,
    name: 'report_layout_manager',
    shortdesc: 'Report Layout Manager',
    summary: 'Visual management of reusable report layouts with QWeb template integration.',
    state: 'installed',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Customizations'
  },
  {
    id: 16,
    name: 'followup_levels_whatsapp',
    shortdesc: 'Salam Account Followup Whatsapp',
    summary: 'Automated WhatsApp payment reminders for credit sales using the follow-up framework.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Accounting'
  },
  {
    id: 19,
    name: 'ai_meta_bridge',
    shortdesc: 'Meta WhatsApp Bridge',
    summary: 'WhatsApp bridge for AI-powered message routing and intelligent agent orchestration.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Productivity'
  },
  {
    id: 20,
    name: 'ai_observability',
    shortdesc: 'AI Observability',
    summary: 'Trace LLM calls, tool usage, and agent responses with detailed metrics and audit logs.',
    state: 'installed',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Administration'
  },
  {
    id: 21,
    name: 'trade_terms',
    shortdesc: 'Trade Terms Management',
    summary: 'Manage trade agreements integrating with purchase, accounting, and approval workflows.',
    state: 'uninstalled',
    application: true,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Sales'
  },
  {
    id: 22,
    name: 'whatsapp_activity',
    shortdesc: 'WhatsApp Activity Scheduler',
    summary: 'Schedule WhatsApp messages as native Odoo activities using customizable templates.',
    state: 'uninstalled',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Productivity'
  },
  {
    id: 23,
    name: 'checker_maker_approver_mixin',
    shortdesc: 'Checker Maker Approver Mixin',
    summary: 'Reusable workflow mixin for implementing Maker/Checker/Approver logic in any module.',
    state: 'installed',
    application: false,
    to_buy: false,
    icon: '',
    module_type: 'custom',
    category: 'Administration'
  }
];

export const CATEGORIES = [
  'Sales',
  'Website',
  'Services',
  'Accounting',
  'Supply Chain',
  'Productivity',
  'Marketing',
  'Human Resources',
  'Shipping Connectors',
  'ESG',
  'Customizations',
  'Administration'
];

